services:
  - type: web
    name: babka-bot-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_server.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GCP_PROJECT_ID
        sync: false
      - key: GCP_LOCATION
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: YOOKASSA_SHOP_ID
        sync: false
      - key: YOOKASSA_SECRET_KEY
        sync: false
  - type: worker
    name: babka-bot-telegram
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GCP_PROJECT_ID
        sync: false
      - key: GCP_LOCATION
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: YOOKASSA_SHOP_ID
        sync: false
      - key: YOOKASSA_SECRET_KEY
        sync: false
